### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sosiristseng** [NTUMitoLab/demo-jupyter-notebooks#1]
- [x] Show and add Python notebooks
 - [x] Create the nbviewer link
 - [x] Export the conda environment for binder
 - [x] Use Jupyter Book to build a website: use [create](https://jupyterbook.org/reference/cli.html#jupyter-book-create) command
